name: Build parsedmarc container

on:
  push:
    branches: [master]
    paths:
      - 'data/Dockerfiles/parsedmarc/**'
  schedule:
    - cron: '0 0 14 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: data/Dockerfiles/parsedmarc/
          tags: |
            ghcr.io/nachotek/parsedmarc:latest
            ghcr.io/nachotek/parsedmarc:${{ github.sha }}
          push: true
